name: DEPLOY - STG
on:
  workflow_dispatch:
jobs:
  s3_cloudfront:
    name: deploy
    uses: GabrielSoares-Dev/workflows/.github/workflows/angular-s3-cloudfront-deploy.yml@master
    with:
      work_dir: ./terraform
      environment: stg
      env_vars_path: env/pstg.tfvars
      node_version: '18.x'
      build_file_path: ./dist/Boilerplate-angular-aws-s3-cloudfront/browser/
    secrets:
      aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID_STG}}
      aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY_STG}}
      aws_region: ${{secrets.AWS_REGION}}
      bucket_name: ${{ secrets.BUCKET_STG }}